spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dzg_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
  security:
    user:
      name: root
      password: 123
server:
  port: 8090
dzg:
  security:
    browser:
      loginType: REDIRECT
#dzg:
#  security:
#    browser:e
#      loginPage: /demo-login.html
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error